### ISSUE TITLE
Test Sharding?

### ISSUE THREAD

**Issue by ianrhamilton** [saucelabs/saucectl-espresso-example#11]
I am trying to shard my espresso tests using the config.yml, however, it is still being executed in a single thread on the same emulator.

My config.yml looks as follows:

```
apiVersion: v1alpha
kind: espresso
sauce:
  region: eu-central-1
  concurrency: 10
  metadata:
    build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./my-debug.apk
  testApp: ./my-debug-androidTest.apk
suites:
  - name: "saucy barista - combined"
    testOptions:
    numShards: 10
    clearPackageData: true
    emulators:
      - name: "Android GoogleApi Emulator"
        clearPackageData: true
        orientation: portrait
        platformVersions:
          - "10.0"

artifacts:
  download:
    when: always
    match:
      - output.xml
    directory: ./reports/
 
```

Do you plan to upload any examples of sharding? 

Thanks in advance,
Ian

**Comment by alexplischke** [comment]
Sharding is very obtuse at the moment.
What you'd actually have to do is this (see https://docs.saucelabs.com/testrunner-toolkit/configuration/espresso#shardindex):
```yaml
  - name: "saucy barista - combined 1/2"
    testOptions:
    numShards: 2
    shardIndex: 0
    clearPackageData: true
    emulators:
      - name: "Android GoogleApi Emulator"
        clearPackageData: true
        orientation: portrait
        platformVersions:
          - "10.0"
  - name: "saucy barista - combined 2/2"
    testOptions:
    numShards: 2
    shardIndex: 1
    clearPackageData: true
    emulators:
      - name: "Android GoogleApi Emulator"
        clearPackageData: true
        orientation: portrait
        platformVersions:
          - "10.0"
```

Effectively multiplying the suite based on the number shards you want to use. It works this way because sharding is performed by espresso and the user in a weird manual way.

However, there's some good news in this! We are actively working on sharding automatically, so that all you have to do is specify `numShards`, for which you may want to follow this PR --> https://github.com/saucelabs/saucectl/pull/343
